# environment/conda.yml
name: churn-env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - scikit-learn
    - pandas
    - azureml-mlflow
    - joblib # Good to have for saving models